### ISSUE TITLE
Can this potentially modified to scrape sample pack metadata from the Sounds catalogue?

### ISSUE THREAD

**Issue by itsBREX** [j-n-f/silly-beatport-scraper#1]
Instead of searching for individual files it could search for the pack name based on the folder name / title the individual sounds are in?

Been trying to find something that will do this and this seems to be the closest thing yet.

**Comment by j-n-f** [comment]
It certainly could. The issue I've had maintaining this is that beatport is constantly updating the HTML structure of their page. I've stepped back for a bit trying to think of a better way to design it. If you look at the source code, everything is basically hard-coded. There needs to be a way to make the scraper reasonably generic so that when the page content changes form, only a scraper configuration needs to change.
